[tool.poetry]
name = "sbot"
version = "0.10.1"
description = "SourceBots API"
authors = ["SourceBots <hello@sourcebots.co.uk>"]
readme = "README.md"
repository = "https://github.com/sourcebots/sbot"
homepage = "https://sourcebots.co.uk"
documentation = "https://docs.sourcebots.co.uk"
classifiers = [
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Typing :: Typed",
    "Topic :: Education",
]

[tool.poetry.dependencies]
python = "^3.7"
j5 = {version = "^1.0.0.rc1", allow-prereleases = true}
j5-zoloto = "^0.3.0"

[tool.poetry.dev-dependencies]
flake8 = "*"
flake8-commas = "*"
flake8-comprehensions = "*"
flake8-debugger = "*"
flake8-docstrings = "*"
flake8-isort = "*"
flake8-mutable = "*"
flake8-todo = "*"
mypy = "*"
pytest = "*"
pytest-cov = "*"
rope = "*"
isort = {version = "^5.8.0",extras = ["pyproject"]}
sphinx = "^4.3.2"
sphinx-rtd-theme = "^1.0.0"
recommonmark = "*"
sphinx-markdown-tables = "*"

[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "sbot/_version.py"

[tool.setuptools]
packages = ["sbot"]

[project]
name = "sbot"
dynamic = ["version"]
requires-python = ">=3.8"
dependencies = [
    "pyserial >=3,<4",
    "april_vision >=2,<3",
]

[project.optional-dependencies]
dev = [
    "flake8",
    "isort",
    "mypy",
    "build",
    "types-pyserial",
    "typing-extensions; python_version<'3.10'",
    "pytest",
    "pytest-cov",
]
