name: Lint & build

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py_version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.py_version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[dev,vision]
    - name: Lint
      run: |
        make lint
    - name: Isort
      run: |
        make isort-check
    - name: Typecheck
      run: |
        make type
    - name: Run tests
      run: |
        make test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip build
        # Install package to generate version info
        python -m pip install .
    - name: Build package
      run: |
        make build
    - name: Save built package
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: |
          dist
    - name: Publish to PyPi
      if: ${{ github.ref_type	== 'tag' }}
      uses: pypa/gh-action-pypi-publish@v1.6.4
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        print_hash: true
